# Generated by Django 5.2.3 on 2025-06-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_answer', models.ImageField(blank=True, null=True, upload_to='survey_images/')),
            ],
        ),
    ]
