# Generated by Django 5.2.3 on 2025-06-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDQ', '0003_question_survey_remove_surveyresponse_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
