# Generated by Django 5.2.3 on 2025-06-24 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDQ', '0004_survey_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text'), ('file', 'File Upload'), ('mcq', 'Multiple Choice')], default='text', max_length=20),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='DDQ.question')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='choice_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DDQ.choice'),
        ),
    ]
